# **Array**

In [ ]:
import array as arr
import numpy as np

In [ ]:
numbers = arr.array('i',[10,20,30])
print(numbers)
print(numbers[:1])
numbers[0] = 40
print(numbers)


array('i', [10, 20, 30])
array('i', [10])
array('i', [40, 20, 30])


In [ ]:
# We can use Tuple instead of list as well.
my_tuple = (-1,0,1)
my_array = np.array(my_tuple)
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

#add the integer  to the end of numbers

In [ ]:
numbers.append(100)
print(numbers)
# also we can do this
numbers.extend([40,50,60])
print(numbers)

array('i', [40, 20, 30, 100])
array('i', [40, 20, 30, 100, 40, 50, 60])


# addition

In [ ]:
print(numbers[2] + numbers[3])

130


## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>

In [ ]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

In [ ]:
# Subtracting two arrays
arr - arr

array([0, 0, 0, 0, 0])

In [ ]:
# Multiplication
arr * arr

array([ 0,  1,  4,  9, 16])

In [ ]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

<ipython-input-86-8ce08d18f8cd>:2: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.])

In [ ]:
# Power of all the elements in an array
arr ** 2

array([ 0,  1,  4,  9, 16])

In [ ]:
# Multiplication with scalar
2 * arr #[0, 1, 2, 3, 4]

array([0, 2, 4, 6, 8])

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>

In [ ]:
arr = [4, 16, 25, 36]

In [ ]:
# Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
# max and min values
np.max(arr), np.min(arr)

(4, 0)

In [ ]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# new sample list

In [ ]:
a = [ 21,34,16,19,100, 26,29,41,38,59]
ard = np.array(a)
print(ard)

[ 21  34  16  19 100  26  29  41  38  59]


In [ ]:
# the number of axes (dimensions) of the array
a = np.ndim(ard)
print(a)
# the dimensions of the array
b = np.shape(ard)
print(b)
# the total number of elements of the array
c = np.size(ard)
print(c)
# step/interval
print(ard[1:7:2]) # 1 means 1 index theke suru hobe ,7 means 0-6 index porjonto cholbe,2 means 1 ghor bad diye diye jabe 1 theke 6 porjonto

1
(10,)
10
[34 19 26]


# arange()
* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval

In [ ]:
np.arange(0,10) # similar to range() in Python, not including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# We can give the step
np.arange(0,11,2)
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

## Categorigal daa jonno

In [ ]:
a2 = np.array(['apple', 'banana', 'cherry'])
print(a2)

['apple' 'banana' 'cherry']


In [ ]:
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
a4 = np.array([1.1, 2.1, 3.1])
print(a4)
newarr = a4.astype('i')# integer a convert korar jonno
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
[1 2 3]
int32


# `linspace()`
Return evenly spaced numbers over a specified interval.<br>


In [ ]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 15, 9) # 9 ta number dibe. 9 ta number ar difference same i thakbe

array([ 1.  ,  2.75,  4.5 ,  6.25,  8.  ,  9.75, 11.5 , 13.25, 15.  ])

In [ ]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(9, 15, 20, retstep=True)  # redstep true diye ader difference ta niche ber kore dey 0.3157894736842105
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [ ]:
np.linspace(0,15,30)

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

# lower, upper

In [ ]:
# (lower, upper, interval)
d = np.arange(10,30,3) # 10 theke suru hobe 30 ghor porjonto cholbe 3 ghor bard diye diye
print(d)
 #linear space (lower, upper, no of position)
e =np.linspace(10, 30, 11) # 10 lower 30 upper 11 means total 11 ta number dibe
print(e)
# # 10 numbers from 0 to 2 , log space
e1 = np.logspace(0,2,10)
print(e1)
# returns exponential value
h = np.exp(4)
print(h)

[10 13 16 19 22 25 28]
[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]
[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]
54.598150033144236


## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

#`zeros()`

* We want to create an array with **all zeros**<br>

In [ ]:
print(np.zeros(9))

np.zeros((4,6)) #(no_row, no_col) passing a tuple

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

 # `ones()`
* We want to create an array with **all ones**<br>

In [ ]:
print(np.ones(3))
np.ones((4,6)) #(no_row, no_col) passing a tuple|

[1. 1. 1.]


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## `eye()`# Identity matrix
Creates an identity matrix must be a square matrix, which is useful in several linear algebra problems.
* Return a 2-D array with **ones on the diagonal and zeros elsewhere.**

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# * reshape(), max(), min(), argmax(), argmin()

## `Reshape()`
Returns an array containing the same data with a new shape.

In [ ]:
array_arange = np.arange(16)
print(array_arange)
array_ranint = np.random.randint(0,100,10)
array_ranint

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([57, 35, 65, 35, 86, 67, 27, 29, 86, 71])

In [ ]:
reshape_test=array_arange.reshape(4,4) # any other num will give error
reshape_test

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [ ]:
a = [ 21,34,16,19,100, 26,29,41,38,59]
ard = np.array(a)
print(ard)

[ 21  34  16  19 100  26  29  41  38  59]


In [ ]:
print(ard.argmax()) # index print korbe
print(ard.argmin())
print(ard.max())
print(ard.min())

4
2
100
16


### Indexing & slicing of 1-D arrays (vectors)

In [ ]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [ ]:
array_1d[0:3]

array([-10,  -2,   0])

In [ ]:
array_1d[-2]

106

In [ ]:
array_1d[1:-2], array_1d

(array([-2,  0,  2, 17]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [ ]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [ ]:
array_2d= np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# To get a complete row
array_2d[2]

array([ 8,  9, 10, 11])

In [ ]:
array_2d[-4] # -0 and 0 is same inedex

array([ 8,  9, 10, 11])

In [ ]:
# To get an individual element value at row = 5 and column = 2
array_2d[5,2]

22

In [ ]:
# another way
row = 5
column = 2
array_2d[row, column]

22

In [ ]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

22

In [ ]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# 2D array slicing
array_2d[:2,:2] # array_2d[:2,:2].shape gives (2,2), 4 elements for top left corner
#[row:row, column:column] [From 0 row to 1 row, From 0 column to 1 column]
# array_2d[0:2,0:2] is same as array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [ ]:
array_2d[2:4,2:4] # inner slice [From 2 row to 3 row, From 2 column to 3 column]

array([[10, 11],
       [14, 15]])

In [ ]:
array_2d= np.arange(30).reshape(6,5)
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
array_2d[3:, 2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [ ]:
array_2d[5,4]

29

In [ ]:
array_2d[:3,1:2] # array_2d[:3,1:3] for col 1 and 2

array([[ 1],
       [ 6],
       [11]])

In [ ]:
array_2d[2,:] # array_2d[2:3,:] will give the same output

array([10, 11, 12, 13, 14])

In [ ]:
array_2d[2:4,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# **Calculate the sum of all the numbers in array_2d?**

In [ ]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
array_2d.sum()

435

In [ ]:
array_2d.sum(axis=1)# axis =1 row wise sum korbe.

array([ 10,  35,  60,  85, 110, 135])

In [ ]:
array_2d.sum(axis=0) ## axis=0 column wise sum korbe.

array([75, 81, 87, 93, 99])

## **2D array**

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9], [4, 5, 9]]
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [ ]:
f = np.arange(12).reshape(3, 4)  # reshape (row, column)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = [ 21,34,16,19,100, 26,29,41,38,59]
ard = np.array(a)
f2 = ard.reshape (2,5)
print(f2)

[[ 21  34  16  19 100]
 [ 26  29  41  38  59]]


In [ ]:
   # copy array
i = np.copy(f2)
print(i)

[[ 21  34  16  19 100]
 [ 26  29  41  38  59]]


In [ ]:
# convert data into matrix, and split matrix into array
k2 = [[1,2,3],[3,4,5],[7,8,9]]

print(np.mat(k2))
l = np.array_split(k2, 3) # matrix ke abar array ye niye jabe
print(l)

[[1 2 3]
 [3 4 5]
 [7 8 9]]
[array([[1, 2, 3]]), array([[3, 4, 5]]), array([[7, 8, 9]])]


# add column in matrix

In [ ]:
k3 = [[10,20,30],[30,40,50],[70,80,90]]
np.mat(k3)
m = np.column_stack((k2, k3))
print(m)

[[ 1  2  3 10 20 30]
 [ 3  4  5 30 40 50]
 [ 7  8  9 70 80 90]]


In [ ]:
# diagomal data of matrix
n = np.diagonal(m)
print(n)

[1 4 9]


In [ ]:
# split matrix
o = np.arange(0,12).reshape(2, 2,3) # 2=2ta raw, 3 =3 ta column. Mazkhan ar 2= matrix ta ke 2 vag a vag korsi
print(o)



[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
# dsplit
p = np.dsplit(o, 3)
print(p)


[array([[[0],
        [3]],

       [[6],
        [9]]]), array([[[ 1],
        [ 4]],

       [[ 7],
        [10]]]), array([[[ 2],
        [ 5]],

       [[ 8],
        [11]]])]


In [ ]:
# transpose matrix
q = np.array([[1, 2], [3, 4], [5, 6]])
print(q)
print(np.transpose(q))


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]



# NumPy Joining Array

In [ ]:
p1 = np.array([1, 2, 3])
p2 = np.array([4, 5, 6])

p3 = np.concatenate((p1, p2))
print(p3)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1)
q1 = np.array([[1, 2], [3, 4]])
q2 = np.array([[5, 6], [7, 8]])

q3 = np.concatenate((q1, q2), axis=1) #axis =0 hole verticaly  value gulo sajabe. #axis =1 hole horizontaly value gulo sajabe
print(q3)
q3 = np.concatenate((q1, q2), axis=0)
print(q3)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


 Joining Arrays Using Stack Functions

In [ ]:
# Joining Arrays Using Stack Functions
r1 = np.array([1, 2, 3])
r2 = np.array([4, 5, 6])

r3 = np.stack((r1, r2), axis=1)
print(r3)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Stacking Along Rows/ similar to concatanate
s1 = np.array([1, 2, 3])
s2 = np.array([4, 5, 6])

s3 = np.hstack((s1, s2))
print(s3)

# Stacking Along Columns
t1 = np.array([1, 2, 3])
t2 = np.array([4, 5, 6])

t3 = np.vstack((t1, t2))
print(t3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacking Along Height (depth)
u1 = np.array([1, 2, 3])
u2 = np.array([4, 5, 6])

u3 = np.dstack((u1, u2))
print(u3)

[[[1 4]
  [2 5]
  [3 6]]]


## **Random Number Generation**

## Random

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
import random

In [ ]:
np.random.rand(10) # 0 theke 1 ar morthe thakbe. 1 ar besi hobe na

array([0.20721186, 0.76740179, 0.82076564, 0.55153953, 0.98649104,
       0.71562451, 0.62398346, 0.95053407, 0.31127718, 0.71095872])

In [ ]:
np.random.rand(3,2)

array([[0.64348197, 0.77908086],
       [0.9796806 , 0.58607112],
       [0.99441553, 0.32748616]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [ ]:
print(np.random.randn(5)) # randn() ar range -3 theke +3
np.random.randn(10,3) # no tuple, each dimension as a separate argument

[-0.94812392  0.00602771 -0.16452545 -0.77953009 -0.82073448]


array([[-0.92673226, -1.15667181, -0.14648942],
       [-0.14080641, -0.34363023, -0.1198921 ],
       [-0.19082019, -1.9428628 ,  0.15004138],
       [ 0.8898258 , -0.29707755,  0.23624569],
       [-0.93300679,  1.3496395 ,  1.08022653],
       [ 1.84431197,  1.31563938, -0.34760763],
       [ 1.4541803 ,  0.61263819, -1.83190151],
       [-0.93401168,  0.40418209, -1.00052146],
       [ 0.88076671, -0.32486291,  1.19302547],
       [ 0.3769564 ,  0.04125813,  0.5368592 ]])

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100) #returns one random int, 1 inclusive, 100 exclusive

17

In [ ]:
g = random.randrange(0,10)
print(g)

8


In [ ]:
g1 = []
for i in range(0,10):
    n = random.randint(1,30)
    g1.append(n)

print(g1)
print(g)


[20, 11, 21, 1, 8, 19, 5, 24, 7, 26]
8


In [ ]:
# Split the 2D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# Broadcasting (Array morthe onnek gulo cell ke aksathe replace korar porthodi ke broadcasting bole)

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>


In [ ]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Take a slice of the array and set it equal to some number, say 500.<br>

array_1d[0:5] = 500
array_1d
#this will **broadcast the value of 500 to the first 5 elements** of the array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [ ]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [ ]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why? # Yes this work

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [ ]:
array_2d + 300
# array_2d + [300,2], did it work? if not why? # Yes this work

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [ ]:
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [ ]:
array_2d[[0,2]] # 0 ar 2 number raw ke dekhabe

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.]])

In [ ]:
array_2d[[3,0,1]]

array([[  1.,   1.,   1.,   1.],
       [300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.]])

In [ ]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# grabbing rows
array_2d[[2,4]]

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [ ]:
# grabbing columns
#array_2d[:,1:3]  # ata lowest theke highest column porjonto nibe. Tai obbssoi left ta right theke choto hote hobe
array_2d[:,[3,2]] #ata sudhu position column nibe

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18],
       [23, 22]])

In [ ]:
array_2d[:,0:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [ ]:
array_1d = np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_array = array_1d > 3
bool_array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = 0 == array_1d % 2
mod_2_mask_1d

array([False,  True, False,  True, False,  True, False,  True, False,
        True])